FROM local.yf-toolkit-s.tk:5000/buildbase-node:latest as buildbase-node
WORKDIR /app
COPY ./frontend ./frontend
WORKDIR /app/frontend
RUN npm run build

FROM local.yf-toolkit-s.tk:5000/buildbase-py:latest as buildbase-py

### integrate for production ###
FROM python:3.9-slim as product
RUN apt-get update && apt-get install libpq-dev -y --no-install-recommends && apt-get purge -y --auto-remove

COPY --from=buildbase-py /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=buildbase-py /usr/local/bin/uvicorn /usr/local/bin/uvicorn
COPY --from=buildbase-node /app/dist /app/dist

COPY ./backend /app/backend
COPY ./storage/user_icon /app/storage/user_icon

WORKDIR /app
ENV PYTHONPATH=/app/backend
ENV DATABASE_URL=postgres://postgres:postgres@yfdb:5432

CMD ["python","-m","uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "5012"]
# CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "5012"]
# CMD ["python","-m","gunicorn","-w","1","-b","0.0.0.0:5012","-k","uvicorn.workers.UvicornWorker","backend.main:app"]



# COPY --from=buildbase-py /usr/local/lib/python3.9/dist-packages /usr/local/lib/python3.9/site-packages
# ↑ 一部イメージでpythonインストールをするとdist-packagesに格納されるので注意
# その場合、uvicorn/gunicornを直接指定出来ず、python -m uvicornとする必要がある。