FROM python:3.9-slim
RUN apt-get update 
RUN apt-get install gcc libpq-dev -y

# Pythonの依存関係をインストール
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --upgrade -r /app/requirements.txt