version: '2'
services:
  registry:
    # restart: always
    image: registry:latest
    container_name: registry
    ports:
      - "5000:5000"
      # - "443:443"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/local.yf-toolkit-s.tk-chain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/local.yf-toolkit-s.tk-key.pem
    networks:
      yfbuild:
        ipv4_address: 172.20.0.12
    volumes:
      - ./certs:/certs
      - registry:/var/lib/registry

networks:
  yfbuild:
    external: true

volumes:
  registry:
    driver: local
